name: Android

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.24.0

      - name: Setup environment
        run: sudo apt-get install ninja-build build-essential cmake libgtk-3-dev openjdk-8-jdk -y

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: dart pub get

      - name: Generate l10n
        run: flutter gen-l10n

      - name: Try build for Android
        run: flutter build apk
