name: Windows

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.24.3

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: dart pub get

      - name: Generate l10n
        run: flutter gen-l10n

      - name: Try build for Windows
        run: flutter build windows
